name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v4
        #  Set up Node.js environment with the latest LTS version
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

        # Install required Node.js dependencies
      - name: Install dependencies
        run: npm ci

        # Install all browsers for tests to run against
      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
          npx playwright install msedge

        # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

        # Upload Playwright report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
